version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    container_name: golang
    volumes:
      - .:/go/src/app
      - go-modules:/go/pkg/mod
    command: go run main.go

volumes:
    go-modules:
